### PR TITLE
Added Next, Previous buttons to view images

### PR DESCRIPTION
**Pull request by goutamnair7**
Next and previous buttons added to imageviewer activity to make image viewing easier

### CODE REVIEW

**Comment by goutamnair7** [comment]
@godiard Sure, Thanks. Will commit after making new changes.

**Comment by goutamnair7** [comment]
@godiard Ohh, okay. Sure. :+1:

**Comment by goutamnair7** [comment]
@godiard Also, I checked for pep8 in ImageViewerActivity.py and I did not get any errors. So, what are the changes which you made?

**Comment by godiard** [comment]
@goutamnair7 , these are the changes I did: https://github.com/godiard/imageviewer-activity/commit/3611324144a4652bbbd0c19b82748c1ec3d6d9fc

**Comment by goutamnair7** [comment]
@godiard Okay. So, do I make a new commit here or do I make a new pr?

**Comment by godiard** [comment]
Please do a new pr

**Pull request closed without merging**
